### ISSUE TITLE
🚀add an option to limit number of lines shown for added/removed in git {log,diff} etc

### ISSUE THREAD

**Issue by yedhink** [dandavison/delta#156]
Version : delta 0.1.1

Problem
-----------
When adding a file with the number of lines added/removed as continuous/adjacent lines is greater than 'N'(say 100), then the git log or diff seems pretty hard to be read/provides info which is unnecessary and it becomes hard to move around different commits/files in the paged output.

Here is a screenshot showing a part of how `git log -p` looks for a particular file, which's tailwindcss generated file(67247 lines):-  
![result-sprite](https://user-images.githubusercontent.com/31244999/80563412-b9cfdb80-8a08-11ea-9a1f-2b223e3aa8d1.png)

Feature Request
----------------------
Currently i think two possible options are there:-  

1.  Add an option to limit the number of lines shown for added/removed lines when diffing/logging a file. say `delta --limit-added-lines=15 --limit-removed-lines=20`
```css
/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */

/* Document
   ========================================================================== */

/**
 * 1. Correct the line height in all browsers.
 * 2. Prevent adjustments of font size after orientation changes in iOS.
 */

html {
  line-height: 1.15; /* 1 */
  -webkit-text-size-adjust: 100%; /* 2 */
}

.
.  ------------- Limited the number of added lines shown ---------------------------------
.
```
2. Or move ahead with implementing/integrating a better option to move around the diff/log with say keybinds. Say for example - a keybind `n|N` for moving to next/prev file-names/commit-ids within the paged content inorder to avoid recursive keystrokes to move down like mentioned in #50 .
