### ISSUE TITLE
🚀 Better default colors for dark terminal backgrounds

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#481]
I think the default colors for dark terminal backgrounds could be improved. Does anyone have any thoughts about this? Do you have some dark mode colors that you're happy with and would you be willing to share your config? cc @ulwlu @kevinhwang91 @torarnv @infokiller @Kr1ss-XD (please add any others who might have ideas here).

It might also be nice to have a sort of gallery of example configs and screenshots to give people some ideas for configuring and to show what's possible. These could be distributed in the delta repo as named features in a config file, which people could `include`, something like

```gitconfig
[include]
    path = ~/src/delta/etc/themes.conf
```

**Comment by kevinhwang91** [comment]
Thank you for your invitation.
# configs:
```gitconfig
[delta]
    paging=always
    line-numbers = true
    syntax-theme = TwoDark
    width = 1
    minus-style = syntax "#450a15"
    minus-emph-style = syntax "#600818"
    plus-style = syntax "#0b4820"
    plus-emph-style = syntax "#175c2e"
    hunk-header-style = syntax bold
    hunk-header-decoration-style = omit
    file-style = yellow italic
    file-decoration-style = yellow ul
    line-numbers-zero-style = "#4b5263"
    line-numbers-left-format = {nm:^4}
    line-numbers-right-format = {np:^4}
```
# screenshots:
![image](https://user-images.githubusercontent.com/17562139/103398933-b5e8f000-4b79-11eb-9646-894115b3c300.png)

# terminal-alacritty
```yaml
  # Normal colors
  normal:
    black:   '#202326'
    red:     '#d41a1a'
    green:   '#12963d'
    yellow:  '#fbb829'
    blue:    '#2c78bf'
    magenta: '#985fc5'
    cyan:    '#259cc1'
    white:   '#bbbbbb'

  # Bright colors
  bright:
    black:   '#5e6c7b'
    red:     '#f75341'
    green:   '#58c379'
    yellow:  '#e1d359'
    blue:    '#429ae5'
    magenta: '#af85ef'
    cyan:    '#62c1d8'
    white:   '#d3dae3'
```
