### ISSUE TITLE
🐛 Not picking custom bat theme

### ISSUE THREAD

**Issue by hbarcelos** [dandavison/delta#953]
### Context

```
$ bat --version          
> bat 0.19.0 (59a8f58b)

$ delta --version           
> delta 0.11.3
```

### Description

I've added a custom theme to `bat` as instructed in their docs. I've run `bat cache --build` and if I run `bat --list-themes | cat` I see the following list:

```
1337
Coldark-Cold
Coldark-Dark
DarkNeon
Dracula
GitHub
Monokai Extended
Monokai Extended Bright
Monokai Extended Light
Monokai Extended Origin
Nord
OneHalfDark
OneHalfLight
Solarized (dark)
Solarized (light)
Sublime Snazzy
TwoDark
Visual Studio Dark+
ansi
base16
base16-256
gruvbox-dark
gruvbox-light
polar-ice <-------- this is my theme!
zenburn
```

When using `bat` my custom theme works as expected. However, if I run `delta --list-syntax-themes`, I get:

```
Light syntax themes:
    GitHub
    Monokai Extended Light
    OneHalfLight
    Solarized (light)
    gruvbox-light

Dark syntax themes:
    1337
    Coldark-Cold
    Coldark-Dark
    DarkNeon
    Dracula
    Monokai Extended
    Monokai Extended Bright
    Monokai Extended Origin
    Nord
    OneHalfDark
    Solarized (dark)
    Sublime Snazzy
    TwoDark
    Visual Studio Dark+
    ansi
    base16
    base16-256
    gruvbox-dark
    zenburn
```

No `polar-ice` theme as I would expect.

In my `themes.gitconfig` file I have:

```toml
[delta "polar-ice-bear"]
    dark = true
    syntax-theme = polar-ice
    file-style = bold yellow
    file-decoration-style = yellow ol ul
    hunk-label = @
    hunk-header-style = line-number syntax
    hunk-header-file-style = magenta
    hunk-header-line-number-style = magenta
    hunk-header-decoration-style = none
    file-modified-label = ✎
    file-removed-label = ✖
    file-added-label = ✚
    file-copied-label = ⎘
    file-renamed-label = ➜
    minus-style = red
    minus-emph-style = lightgrey "#e11418"
    plus-style = green
    plus-emph-style = lightgrey "#61ab16"
    line-numbers = true
    line-numbers-minus-style = red
    line-numbers-zero-style = "#697981"
    line-numbers-plus-style = green
    line-numbers-left-format = "{nm:>4}┊"
    line-numbers-right-format = "{np:>4}│"
    line-numbers-left-style = "#697981"
    line-numbers-right-style = "#697981"
```

So the obvious result is that although the diff colors are correct, the theme for syntax highlighting is not working.

![image](https://user-images.githubusercontent.com/16565602/152986693-de43574a-c745-4e89-a9a9-d3b83962206e.png)
