### ISSUE TITLE
🚀 Add support for `hunk-label-style`

### ISSUE THREAD

**Issue by waldyrious** [dandavison/delta#968]
Currently, the color of `hunk-label` respects `hunk-header-file-style`, which defaults to blue. This produces a consistent coloring when the filename is included in the hunk headers, via the special "file" keyword: 

```toml
[delta]
    # ...
	hunk-header-style = "file line-number syntax"
	hunk-label = "Foobar"
	hunk-header-line-number-style = "red"
```

![Screenshot from 2022-02-15 19-13-47](https://user-images.githubusercontent.com/478237/154133792-3ecad246-3c2c-4399-8560-dc5802a78f97.png)

But if I don't include "file" in `hunk-header-style`, I would like it to match the color of the remainder of the hunk header (e.g. the line number). I would have expected to use a `hunk-label-style` config to do so, but that has no effect:

```toml
[delta]
    # ...
	hunk-header-style = "line-number syntax"
	hunk-label = "Foobar"
	hunk-header-line-number-style = "red"
	hunk-label-style = "red"
```

![Screenshot from 2022-02-15 19-18-47](https://user-images.githubusercontent.com/478237/154133806-4106ae1a-eb72-408a-8785-99b96ce308d9.png)

I can work around this by setting `hunk-header-file-style`:

```toml
[delta]
    # ...
	hunk-header-style = "line-number syntax"
	hunk-label = "Foobar"
	hunk-header-line-number-style = "red"
	hunk-header-file-style = "red"
```

![Screenshot from 2022-02-15 19-19-25](https://user-images.githubusercontent.com/478237/154133809-8f130801-d0ee-40fd-af37-db961d4810ac.png)

...but that's awkward because I'm not using "file" in the hunk header at all.

Ideally, there should be a dedicated `hunk-label-style` for styling the hunk prefix.

(By the way, why isn't this config called `hunk-header-label`? That would be more consistent with the other configurations.)
